services:
  db:
    image: postgres:14
    container_name: postgeres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: runners_db
    volumes:
      - ./dbscripts:/docker-entrypoint-initdb.d
